draw_config:
  # key_h: 60
  combo_w: 30
  combo_h: 14
  small_pad: 8
  shrink_wide_legends: 5
  glyph_tap_size: 24
  glyph_hold_size: 10
  glyph_shifted_size: 10
  arc_radius: 0
  # separate_combo_diagrams: bool = False
  # draw_key_sides: True
  append_colon_to_layer_header: False

  svg_extra_style: |
    .none, .trans, .ghost {
      opacity: 0.8;
    }

    /* color accent for combo boxes */
    rect.combo, rect.combo-separate {
        fill: #CCDDFF;
        stroke: #99AACC;
    }

    /* rect.held, rect.combo.held { */
    .held {
      opacity: 1.0;
      filter: drop-shadow(0px 0px 6px #4FC0D0);  /* #7979EC); */
    }

    text.key.tap {
      font-size: 16px;
      /* font-weight: 900; */
    }

    text.hold, text.shifted {
      font-size: 9px;
      font-weight: normal;
    }

    text.combo {
      font-size: 11px;
      font-weight: bold;
    }

parse_config:
  # mark_alternate_layer_activators: true
  # sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: ""

  raw_binding_map:
    "&kp LC(X)":
      tap: CUT
      hold: $$mdi:content-cut$$
    "&kp LC(C)":
      tap: COPY
      hold: $$mdi:content-copy$$
    "&kp LC(V)":
      tap: PASTE
      hold: $$mdi:content-paste$$

    "&kp LSC(Z)":
      tap: REDO
      hold: $$mdi:redo$$
    "&kp LC(Z)":
      tap: UNDO
      hold: $$mdi:undo$$

    "&kp LGS(S)":
      tap: SNIP
      hold: $$mdi:crop$$ # select-drag$$
    "&kp PSCRN":
      tap: PSCRN
      hold: $$mdi:crop$$ # select$$

    "&zoom LG(ESC) 0":
      tap: ZOOM
      hold: $$mdi:magnify$$ # $$mdi:magnify-minus-outline$$

    "&caps_word":
      tap: CAPS # $$mdi:caps-lock$$ # CAPS # hold: $$mdi:close-box$$
    "&bsdl":
      tap: BSPC # $$mdi:backspace-outline$$

    "&lpb":
      tap: "([{" # hold: $$mdi:close-box$$
    "&rpb":
      tap: "}])" # hold: $$mdi:close-box$$

    "&sys_reset":
      tap: RESET
      hold: $$mdi:power$$
    "&bootloader":
      tap: BOOT
      hold: $$mdi:cloud-download-outline$$

    # przełącznik BLE-USB i QWERTY-COLEMAK
    "&out OUT_TOG":
      tap: "BT/USB"
      hold: $$mdi:toggle-switch-outline$$ # $$mdi:keyboard-settings-outline$$
    "&tog COL":
      tap: COLEMAK
      hold: $$mdi:toggle-switch-outline$$ # $$mdi:keyboard-settings-outline$$

    # nawigacja
    "&kp LEFT":
      tap: LEFT
      hold: $$mdi:chevron-left$$
    "&kp RIGHT":
      tap: RIGHT
      hold: $$mdi:chevron-right$$
    "&kp UP":
      tap: UP
      hold: $$mdi:chevron-up$$
    "&kp DOWN":
      tap: DOWN
      hold: $$mdi:chevron-down$$

    "&kp HOME":
      tap: HOME
      hold: $$mdi:page-first$$
    "&kp END":
      tap: END
      hold: $$mdi:page-last$$

    "&kp PG_UP": "PGUP"
    "&kp PG_DN": "PGDN"

    "&bt BT_CLR":
      tap: "BT" # $$mdi:bluetooth$$
      hold: "CLR" # $$mdi:close-box$$

    # wirtualne pulpity + przechodzenie pomiędzy aplikacjami
    "&prev":
      tap: "PREV"
      hold: $$mdi:page-previous-outline$$
    "&next":
      tap: "NEXT"
      hold: $$mdi:page-next-outline$$

    "&none":
      type: none

  zmk_combos:
    caps:
      align: top
      offset: -0.4
