draw_config:
  # key_h: 60
  combo_w: 30
  combo_h: 14
  small_pad: 8
  shrink_wide_legends: 5
  glyph_tap_size: 24
  glyph_hold_size: 10
  glyph_shifted_size: 10
  arc_radius: 0
  # separate_combo_diagrams: False
  # draw_key_sides: True
  append_colon_to_layer_header: False

  svg_extra_style: |
    .none, .trans, .ghost {
      opacity: 0.8;
    }

    /* color accent for combo boxes */
    rect.combo, rect.combo-separate {
        fill: #CCDDFF;
        stroke: #99AACC;
    }

    /* rect.held, rect.combo.held { */
    .held {
      opacity: 1.0;
      filter: drop-shadow(0px 0px 6px #4FC0D0);  /* #7979EC); */
    }

    text.key.tap {
      font-size: 16px;
      /* font-weight: 900; */
    }

    text.hold, text.shifted {
      font-size: 9px;
      font-weight: normal;
    }

    text.combo {
      font-size: 11px;
      font-weight: bold;
    }

parse_config:
  # mark_alternate_layer_activators: true
  # sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: ""

  raw_binding_map:
    "&kp N1":
      tap: "1!"
    "&kp N2":
      tap: "2@"
    "&kp N3":
      tap: "3#"
    "&kp N4":
      tap: "4$"
    "&kp N5":
      tap: "5%"
    "&kp N6":
      tap: "6^"
    "&kp N7":
      tap: "7&"
    "&kp N8":
      tap: "8*"
    "&kp N9":
      tap: "9("
    "&kp N0":
      tap: "0)"


    "&kp COMMA":
      tap: ",<"
    "&kp DOT":
      tap: ".>"
    "&kp SLASH":
      tap: "/?"
    "&kp BSLH":
      tap: "\\|"
    "&kp LBKT":
      tap: "[{"
    "&kp RBKT":
      tap: "]}"
    "&kp GRAVE":
      tap: "`~"
    "&kp APOS":
      tap: "'\""

    # "&kp MINUS":
    #   tap: "- _"

    # "&kp EQUAL":
    #   tap: "= +"

    "&kp SEMI":
      tap: ";:"

    "&kp LC(X)":
      tap: CUT
      hold: $$mdi:content-cut$$
    "&kp LC(C)":
      tap: COPY
      hold: $$mdi:content-copy$$
    "&kp LC(V)":
      tap: PASTE
      hold: $$mdi:content-paste$$

    "&kp LSC(Z)":
      tap: REDO
      hold: $$mdi:redo$$
    "&kp LC(Z)":
      tap: UNDO
      hold: $$mdi:undo$$

    "&kp LSG(S)":
      tap: SNIP
      hold: $$mdi:crop$$ # select-drag$$
    "&kp PSCRN":
      tap: PSCRN
      hold: $$mdi:crop$$ # select$$

    "&kp LCA(UP)":
      tap: IDENT-
      hold: $$mdi:tag-arrow-up$$
    "&kp LCA(DOWN)":
      tap: IDENT+
      hold: $$mdi:tag-arrow-down$$

    "&kp LS(LA(S))":
      tap: GREP

    "&kp LC(F)":
      tap: FIND

    "&kp LC(G)":
      tap: GOTO

    "&kp LC(B)":
      tap: BMRK

    "&kp LG(EQUAL)":
      tap: ZOOM+
      hold: $$mdi:magnify$$ # $$mdi:magnify-plus-outline$$
    "&kp LG(MINUS)":
      tap: ZOOM-
      hold: $$mdi:magnify$$ # $$mdi:magnify-minus-outline$$
    "&kp LG(ESC)":
      tap: EXIT
      # hold: $$mdi:magnify$$ # $$mdi:magnify-minus-outline$$

    "&caps_word":
      tap: CAPS # $$mdi:caps-lock$$ # CAPS # hold: $$mdi:close-box$$

    "&bsdl":
      tap: BSPC # $$mdi:backspace-outline$$

    # "&lpb":
    #   tap: "([{" # hold: $$mdi:close-box$$
    # "&rpb":
    #   tap: "}])" # hold: $$mdi:close-box$$

    # systemowe (Bluetooth, przełącznik BLE-USB i QWERTY-COLEMAK)
    "&out OUT_TOG":
      tap: BT/USB
      hold: $$mdi:toggle-switch-outline$$ # $$mdi:keyboard-settings-outline$$
    "&tog COL":
      tap: COLEMAK
      hold: $$mdi:toggle-switch-outline$$ # $$mdi:keyboard-settings-outline$$

    "&sys_reset":
      tap: RESET
      hold: $$mdi:power$$
    "&bootloader":
      tap: BOOT
      hold: $$mdi:cloud-download-outline$$

    "&bt BT_CLR":
      tap: BT # $$mdi:bluetooth$$
      hold: CLR # $$mdi:close-box$$

    # nawigacja
    "&kp LEFT":
      tap: LEFT
      hold: $$mdi:chevron-left$$
    "&kp RIGHT":
      tap: RIGHT
      hold: $$mdi:chevron-right$$
    "&kp UP":
      tap: UP
      hold: $$mdi:chevron-up$$
    "&kp DOWN":
      tap: DOWN
      hold: $$mdi:chevron-down$$

    "&kp HOME":
      tap: HOME
      hold: $$mdi:page-first$$
    "&kp END":
      tap: END
      hold: $$mdi:page-last$$

    "&kp PG_UP":
      tap: PGUP
      hold: $$mdi:chevron-double-up$$
    "&kp PG_DN":
      tap: PGDN
      hold: $$mdi:chevron-double-down$$

    "&kp LC(LEFT)":
      tap: WORD
      hold: $$mdi:chevron-left-box-outline$$
    "&kp LC(RIGHT)":
      tap: WORD
      hold: $$mdi:chevron-right-box-outline$$

    "&kp LC(SLASH)":
      tap: COMMENT
      # hold: //

    # wirtualne pulpity + przechodzenie pomiędzy aplikacjami
    # "&kp LA(TAB)":
    #   tap: PREV
    #   hold: $$mdi:page-previous-outline$$
    # "&prev":
    #   tap: PREV
    #   hold: $$mdi:page-previous-outline$$
    # "&next":
    #   tap: NEXT
    #   hold: $$mdi:page-next-outline$$

    # "&dlequal":
    #   tap: "≤"

    # "&dequal":
    #   tap: ":="

    # "&dgequal":
    #   tap: "≥"

    "&none":
      type: none

  zmk_combos:
    caps:
      align: bottom
      # offset: -0.20

    # under:
    #   offset: 0.20

    # esc:
    #   align: top
    #   offset: 0.12
    #   width: 100

    # ins:
    #   align: top
    #   offset: -0.2
    #   width: 85

    # del:
    #   align: top
    #   offset: -0.2
    #   width: 85

    # ent:
    #   align: top
    #   offset: 0.12
    #   width: 100

    # lbrc:
    #   dendron: true

    # rbrc:
    #   dendron: true

    # lpar:
    #   dendron: true

    # rpar:
    #   dendron: true

    # div:
    #   dendron: true

    # mul:
    #   dendron: true

    exit:
      align: top
      offset: 0.15
      width: 30

    tab:
      width: 30

    bspc:
      width: 30

    del:
      width: 30

    dif:
      tap: "/"
      width: 30

    comment:
      width: 40
