manifest:
  remotes:
    - name: urob                            # - name: zmkfirmware
      url-base: https://github.com/urob     #   url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: elpekenin                       
      url-base: https://github.com/elpekenin
  projects:
    - name: zmk
      remote: urob                          # remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-userspace
      remote: elpekenin
      revision: main
  self:
    path: config
