manifest:
  remotes:
    - name: urob                            # - name: zmkfirmware
      url-base: https://github.com/urob     #   url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: urob                          # remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob
      revision: main
  self:
    path: config
